import { createContext, useContext, useState, ReactNode } from 'react';

type Language = 'en' | 'es' | 'zh' | 'pl' | 'ar';

interface LanguageContextType {
  language: Language;
  setLanguage: (language: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const translations = {
  en: {
    // Navigation
    'nav.home': 'Home',
    'nav.about': 'About',
    'nav.policies': 'Policies',
    'nav.campaign': 'Campaign',
    'nav.community': 'Community',
    'nav.volunteer': 'Volunteer',
    
    // Homepage
    'home.title': 'Your Future U.S. Senator Lives Among the People',
    'home.tagline': "It's not Red vs. Blue, it's oligarchs vs. you.",
    'home.getInvolved': 'Get Involved',
    'home.donate': 'Donate',
    'home.quote': "I'm running for U.S. Senate because I believe the government should promote equality for everyone.",
    'home.fightingTitle': 'Fighting for Our Future',
    'home.costOfLiving': 'Lowering Cost of Living',
    'home.costOfLivingDesc': 'Making housing, healthcare, and education affordable for every family through bold policy action.',
    'home.environment': 'Environmental Policy',
    'home.environmentDesc': 'Protecting our planet while creating good-paying green jobs for the next generation.',
    'home.pinkTax': 'Elimination of The Pink Tax',
    'home.pinkTaxDesc': 'Ending gender-based pricing discrimination once and for all through federal legislation.',
    'home.learnMore': 'Learn More',
    'home.theIssues': 'The Issues',
    'home.joinMovement': 'Join the Movement',
    'home.joinDesc': 'Together, we can build a future where every person has the opportunity to thrive.',
    'home.donateToday': 'Donate Today',
    'home.statsIllinois': 'Illinois Residents',
    'home.statsElection': 'Election Year',
    'home.statsVoice': 'Voice for Change',
    'home.readyFight': 'Ready to Fight Together?',
    'home.fightDesc': 'This campaign is about building a movement for change. Join thousands of Illinois residents who are ready to fight for a better future.',
    'home.supportCampaign': 'Support the Campaign',
    
    // About Page
    'about.meetJump': 'Meet Jump',
    'about.policies': 'Policies',
    'about.policiesDesc': "Jump's comprehensive policy platform focuses on economic justice, environmental responsibility, and equality for all Americans.",
    'about.viewPlatform': 'View Platform',
    'about.getInvolved': 'Get Involved',
    'about.myPolicies': 'My Policies',
    'about.bioText': 'Jump was born and raised in Chicago. As an Illinois Native, he is uniquely equipped to understand and address the challenges of working class Illinoisans.',
    'about.economicJustice': 'Economic Justice',
    'about.healthcareAccess': 'Healthcare Access',
    'about.workingClassFamilies': 'Working Class Families',
    'about.climateAction': 'Climate Action',
    'about.reproductiveRights': 'Reproductive Rights',
    'about.readyToFight': 'Ready to Fight Together?',
    'about.buildingMovement': 'This campaign is about building a movement for change. Join thousands of Illinois residents who are ready to fight for a better future.',
    'about.joinMovement': 'Join the Movement',
    'about.supportCampaign': 'Support the Campaign',
    
    // Policies Page
    'policies.myPolicies': 'My Policies',
    'policies.championing': 'Championing Progressive Values for Illinois',
    'policies.economicJusticeTitle': 'Economic Justice',
    'policies.economicJusticeDesc': 'Fighting for fair wages, worker rights, and economic opportunities that build strong communities.',
    'policies.healthcareAccessTitle': 'Healthcare Access',
    'policies.healthcareAccessDesc': 'Ensuring every Illinoisan has access to affordable, quality healthcare as a fundamental right.',
    'policies.educationEquityTitle': 'Education Equity',
    'policies.educationEquityDesc': 'Investing in public education and making college affordable for working families.',
    'policies.workingFamiliesTitle': 'Working Families',
    'policies.workingFamiliesDesc': 'Supporting policies that help working families thrive in today\'s economy.',
    'policies.climateActionTitle': 'Climate Action',
    'policies.climateActionDesc': 'Leading the fight against climate change with clean energy jobs and environmental justice.',
    
    // Community Page
    'community.joinCommunity': 'Join Our Community',
    'community.connectWith': 'Connect with Illinois residents building a grassroots movement for economic justice and progressive change.',
    'community.followCampaign': 'Follow the Campaign',
    'community.stayConnected': 'Stay connected with daily updates, behind-the-scenes content, and live events',
    'community.upcomingEvents': 'Upcoming Events',
    'community.joinEvents': 'Join us at campaign events across Illinois to meet fellow supporters and learn more about our movement.',
    'community.eventCalendar': 'Event Calendar',
    'community.stayUpdated': 'Stay updated with all upcoming campaign events and activities.',
    'community.viewCalendar': 'View Full Calendar',
    'community.contactEvents': 'Contact for Events',
    'community.orderMerch': 'Order Merch',
    'community.showSupport': 'Show your support with official campaign merchandise',
    'community.tshirts': 'T-Shirts',
    'community.buttonsStickers': 'Buttons & Stickers',
    'community.yardSign': 'Order a Yard Sign',
    'community.stayInformed': 'Stay Informed',
    'community.weeklyUpdates': 'Get weekly updates on campaign progress, policy positions, and upcoming events delivered to your inbox.',
    'community.enterEmail': 'Enter your email',
    'community.subscribe': 'Subscribe',
    'community.privacyNote': 'We respect your privacy. Unsubscribe at any time.',
    'community.bePartMovement': 'Be Part of the Movement',
    'community.realChange': 'Real change happens when communities organize together. Join thousands of Illinois residents fighting for progressive policies.',
    'community.volunteerToday': 'Volunteer Today',
    'community.contactUs': 'Contact Us',
    
    // Campaign Page  
    'campaign.howCanHelp': 'How Can You Help?',
    'campaign.joinMovement': 'Join our movement to bring real change to Illinois. Every contribution, every volunteer hour, and every voice matters in our fight for justice and equality.',
    'campaign.buildFuture': 'Together, we can build a better future for all Illinoisans.',
    'campaign.actionsNeeded': 'Actions Needed Now',
    'campaign.joinVolunteerTeam': 'Join Our Volunteer Team',
    'campaign.volunteering': 'Volunteering',
    'campaign.beChange': 'Be the change you want to see. Join our dedicated team of volunteers working to transform Illinois communities.',
    'campaign.donations': 'Donations',
    'campaign.financialSupport': 'Your financial support helps us reach more voters, organize more events, and amplify our message across Illinois.',
    'campaign.press': 'Press',
    
    // Volunteer Page
    'volunteer.joinTeam': 'Join Our Team',
    'volunteer.makeChange': 'Ready to make a real difference in Illinois? Join our grassroots movement and help build a more just and equitable future for all.',
    'volunteer.getInvolved': 'Get Involved',
    'volunteer.volunteerInterests': 'Volunteer Interests',
    'volunteer.firstName': 'First Name',
    'volunteer.lastName': 'Last Name',
    'volunteer.email': 'Email',
    'volunteer.phone': 'Phone Number',
    'volunteer.zipCode': 'Zip Code',
    'volunteer.submit': 'Submit',
    
    // Footer
    'footer.connect': 'Connect',
    'footer.contact': 'Contact',
    'footer.signUpUpdates': 'Sign Up for Updates',
  },
  es: {
    // Navigation
    'nav.home': 'Inicio',
    'nav.about': 'Acerca de',
    'nav.policies': 'Políticas',
    'nav.campaign': 'Campaña',
    'nav.community': 'Comunidad',
    'nav.volunteer': 'Voluntario',
    
    // Homepage
    'home.title': 'Tu Futuro Senador de EE.UU. Vive Entre la Gente',
    'home.tagline': 'No es Rojo contra Azul, son oligarcas contra ti.',
    'home.getInvolved': 'Participa',
    'home.donate': 'Donar',
    'home.quote': 'Me postulo para el Senado de EE.UU. porque creo que el gobierno debe promover la igualdad para todos.',
    'home.fightingTitle': 'Luchando por Nuestro Futuro',
    'home.costOfLiving': 'Reducir el Costo de Vida',
    'home.costOfLivingDesc': 'Hacer que la vivienda, la atención médica y la educación sean asequibles para todas las familias a través de acciones políticas audaces.',
    'home.environment': 'Política Ambiental',
    'home.environmentDesc': 'Proteger nuestro planeta mientras creamos empleos verdes bien remunerados para la próxima generación.',
    'home.pinkTax': 'Eliminación del Impuesto Rosa',
    'home.pinkTaxDesc': 'Acabar con la discriminación de precios basada en el género de una vez por todas a través de la legislación federal.',
    'home.learnMore': 'Aprende Más',
    'home.theIssues': 'Los Temas',
    'home.joinMovement': 'Únete al Movimiento',
    'home.joinDesc': 'Juntos, podemos construir un futuro donde cada persona tenga la oportunidad de prosperar.',
    'home.donateToday': 'Dona Hoy',
    'home.statsIllinois': 'Residentes de Illinois',
    'home.statsElection': 'Año Electoral',
    'home.statsVoice': 'Voz para el Cambio',
    'home.readyFight': '¿Listo para Luchar Juntos?',
    'home.fightDesc': 'Esta campaña se trata de construir un movimiento para el cambio. Únete a miles de residentes de Illinois que están listos para luchar por un futuro mejor.',
    'home.supportCampaign': 'Apoya la Campaña',
    
    // About Page
    'about.meetJump': 'Conoce a Jump',
    'about.policies': 'Políticas',
    'about.policiesDesc': 'La plataforma política integral de Jump se enfoca en la justicia económica, la responsabilidad ambiental y la igualdad para todos los estadounidenses.',
    'about.viewPlatform': 'Ver Plataforma',
    'about.getInvolved': 'Participar',
    'about.myPolicies': 'Mis Políticas',
    'about.bioText': 'Jump nació y se crió en Chicago. Como nativo de Illinois, está excepcionalmente equipado para entender y abordar los desafíos de los illinoisanos de clase trabajadora.',
    'about.economicJustice': 'Justicia Económica',
    'about.healthcareAccess': 'Acceso a la Salud',
    'about.workingClassFamilies': 'Familias de Clase Trabajadora',
    'about.climateAction': 'Acción Climática',
    'about.reproductiveRights': 'Derechos Reproductivos',
    'about.readyToFight': '¿Listo para Luchar Juntos?',
    'about.buildingMovement': 'Esta campaña se trata de construir un movimiento para el cambio. Únete a miles de residentes de Illinois que están listos para luchar por un futuro mejor.',
    'about.joinMovement': 'Únete al Movimiento',
    'about.supportCampaign': 'Apoya la Campaña',
    
    // Policies Page
    'policies.myPolicies': 'Mis Políticas',
    'policies.championing': 'Defendiendo Valores Progresivos para Illinois',
    'policies.economicJusticeTitle': 'Justicia Económica',
    'policies.economicJusticeDesc': 'Luchando por salarios justos, derechos de los trabajadores y oportunidades económicas que construyan comunidades fuertes.',
    'policies.healthcareAccessTitle': 'Acceso a la Salud',
    'policies.healthcareAccessDesc': 'Asegurando que cada illinoisense tenga acceso a atención médica asequible y de calidad como un derecho fundamental.',
    'policies.educationEquityTitle': 'Equidad Educativa',
    'policies.educationEquityDesc': 'Invirtiendo en educación pública y haciendo que la universidad sea asequible para las familias trabajadoras.',
    'policies.workingFamiliesTitle': 'Familias Trabajadoras',
    'policies.workingFamiliesDesc': 'Apoyando políticas que ayuden a las familias trabajadoras a prosperar en la economía actual.',
    'policies.climateActionTitle': 'Acción Climática',
    'policies.climateActionDesc': 'Liderando la lucha contra el cambio climático con empleos de energía limpia y justicia ambiental.',
    
    // Community Page
    'community.joinCommunity': 'Únete a Nuestra Comunidad',
    'community.connectWith': 'Conéctate con residentes de Illinois construyendo un movimiento de base para la justicia económica y el cambio progresivo.',
    'community.followCampaign': 'Sigue la Campaña',
    'community.stayConnected': 'Mantente conectado con actualizaciones diarias, contenido detrás de escena y eventos en vivo',
    'community.upcomingEvents': 'Próximos Eventos',
    'community.joinEvents': 'Únete a nosotros en eventos de campaña en todo Illinois para conocer a otros partidarios y aprender más sobre nuestro movimiento.',
    'community.eventCalendar': 'Calendario de Eventos',
    'community.stayUpdated': 'Mantente actualizado con todos los próximos eventos y actividades de campaña.',
    'community.viewCalendar': 'Ver Calendario Completo',
    'community.contactEvents': 'Contactar para Eventos',
    'community.orderMerch': 'Ordenar Mercancía',
    'community.showSupport': 'Muestra tu apoyo con mercancía oficial de campaña',
    'community.tshirts': 'Camisetas',
    'community.buttonsStickers': 'Botones y Calcomanías',
    'community.yardSign': 'Ordenar un Letrero de Jardín',
    'community.stayInformed': 'Mantente Informado',
    'community.weeklyUpdates': 'Recibe actualizaciones semanales sobre el progreso de la campaña, posiciones políticas y próximos eventos en tu bandeja de entrada.',
    'community.enterEmail': 'Ingresa tu correo electrónico',
    'community.subscribe': 'Suscribirse',
    'community.privacyNote': 'Respetamos tu privacidad. Cancela la suscripción en cualquier momento.',
    'community.bePartMovement': 'Sé Parte del Movimiento',
    'community.realChange': 'El cambio real ocurre cuando las comunidades se organizan juntas. Únete a miles de residentes de Illinois luchando por políticas progresivas.',
    'community.volunteerToday': 'Voluntario Hoy',
    'community.contactUs': 'Contáctanos',
    
    // Campaign Page  
    'campaign.howCanHelp': '¿Cómo Puedes Ayudar?',
    'campaign.joinMovement': 'Únete a nuestro movimiento para traer un cambio real a Illinois. Cada contribución, cada hora de voluntariado y cada voz importa en nuestra lucha por la justicia y la igualdad.',
    'campaign.buildFuture': 'Juntos, podemos construir un futuro mejor para todos los habitantes de Illinois.',
    'campaign.volunteering': 'Voluntariado',
    'campaign.beChange': 'Sé el cambio que quieres ver. Únete a nuestro equipo dedicado de voluntarios trabajando para transformar las comunidades de Illinois.',
    'campaign.donations': 'Donaciones',
    'campaign.financialSupport': 'Tu apoyo financiero nos ayuda a llegar a más votantes, organizar más eventos y amplificar nuestro mensaje en todo Illinois.',
    'campaign.press': 'Prensa',
    
    // Volunteer Page
    'volunteer.joinTeam': 'Únete a Nuestro Equipo',
    'volunteer.makeChange': '¿Listo para hacer una diferencia real en Illinois? Únete a nuestro movimiento de base y ayuda a construir un futuro más justo y equitativo para todos.',
    'volunteer.getInvolved': 'Involúcrate',
    'volunteer.volunteerInterests': 'Intereses de Voluntariado',
    'volunteer.firstName': 'Nombre',
    'volunteer.lastName': 'Apellido',
    'volunteer.email': 'Correo Electrónico',
    'volunteer.phone': 'Número de Teléfono',
    'volunteer.zipCode': 'Código Postal',
    'volunteer.submit': 'Enviar',
    
    // Footer
    'footer.connect': 'Conectar',
    'footer.contact': 'Contacto',
    'footer.signUpUpdates': 'Suscribirse a Actualizaciones',
  },
  zh: {
    // Navigation
    'nav.home': '首页',
    'nav.about': '关于',
    'nav.policies': '政策',
    'nav.campaign': '竞选',
    'nav.community': '社区',
    'nav.volunteer': '志愿者',
    
    // Homepage
    'home.title': '您未来的美国参议员生活在人民中间',
    'home.tagline': '这不是红与蓝的对立，而是寡头与您的对立。',
    'home.getInvolved': '参与其中',
    'home.donate': '捐赠',
    'home.quote': '我竞选美国参议员是因为我相信政府应该促进每个人的平等。',
    'home.fightingTitle': '为我们的未来而战',
    'home.costOfLiving': '降低生活成本',
    'home.costOfLivingDesc': '通过大胆的政策行动使每个家庭都能负担得起住房、医疗保健和教育。',
    'home.environment': '环境政策',
    'home.environmentDesc': '在保护我们的星球的同时为下一代创造高薪绿色工作。',
    'home.pinkTax': '消除粉红税',
    'home.pinkTaxDesc': '通过联邦立法彻底结束基于性别的价格歧视。',
    'home.learnMore': '了解更多',
    'home.theIssues': '议题',
    'home.joinMovement': '加入运动',
    'home.joinDesc': '团结起来，我们可以建设一个每个人都有机会繁荣发展的未来。',
    'home.donateToday': '今天捐赠',
    'home.statsIllinois': '伊利诺伊州居民',
    'home.statsElection': '选举年',
    'home.statsVoice': '变革之声',
    'home.readyFight': '准备好一起战斗吗？',
    'home.fightDesc': '这场竞选是为了建立一个变革运动。加入数千名准备为更美好未来而战的伊利诺伊州居民。',
    'home.supportCampaign': '支持竞选活动',
    
    // About Page
    'about.meetJump': '认识Jump',
    'about.policies': '政策',
    'about.policiesDesc': 'Jump的综合政策平台专注于经济正义、环境责任和所有美国人的平等。',
    'about.viewPlatform': '查看平台',
    'about.getInvolved': '参与其中',
    'about.myPolicies': '我的政策',
    'about.bioText': 'Jump在芝加哥出生长大。作为伊利诺伊州本地人，他具备独特的能力来理解和解决伊利诺伊州工人阶级面临的挑战。',
    'about.economicJustice': '经济正义',
    'about.healthcareAccess': '医疗保健',
    'about.workingClassFamilies': '工人阶级家庭',
    'about.climateAction': '气候行动',
    'about.reproductiveRights': '生殖权利',
    'about.readyToFight': '准备好一起战斗吗？',
    'about.buildingMovement': '这场竞选是为了建立一个变革运动。加入数千名准备为更美好未来而战的伊利诺伊州居民。',
    'about.joinMovement': '加入运动',
    'about.supportCampaign': '支持竞选活动',
    
    // Policies Page
    'policies.myPolicies': '我的政策',
    'policies.championing': '为伊利诺伊州倡导进步价值观',
    'policies.economicJusticeTitle': '经济正义',
    'policies.economicJusticeDesc': '为公平工资、工人权利和建设强大社区的经济机会而战。',
    'policies.healthcareAccessTitle': '医疗保健',
    'policies.healthcareAccessDesc': '确保每个伊利诺伊州人都能获得负担得起、高质量的医疗保健作为基本权利。',
    'policies.educationEquityTitle': '教育公平',
    'policies.educationEquityDesc': '投资公共教育，让工人家庭能够负担得起大学教育。',
    'policies.workingFamiliesTitle': '工人家庭',
    'policies.workingFamiliesDesc': '支持帮助工人家庭在今天的经济中繁荣发展的政策。',
    'policies.climateActionTitle': '气候行动',
    'policies.climateActionDesc': '通过清洁能源工作和环境正义引领对抗气候变化的斗争。',
    
    // Community Page
    'community.joinCommunity': '加入我们的社区',
    'community.connectWith': '与为经济正义和进步变革建立草根运动的伊利诺伊州居民建立联系。',
    'community.followCampaign': '关注竞选',
    'community.stayConnected': '通过每日更新、幕后内容和现场活动保持联系',
    'community.socialMedia': '社交媒体',
    'community.tiktok': 'TikTok',
    'community.linkedin': 'LinkedIn',
    'community.youtube': 'YouTube',
    'community.merchandise': '商品',
    'community.orderMerch': '订购商品',
    'community.showSupport': '通过官方竞选商品展示您的支持',
    'community.tshirts': 'T恤',
    'community.buttonsStickers': '徽章和贴纸',
    'community.yardSign': '订购院子标牌',
    'community.stayInformed': '保持了解',
    'community.weeklyUpdates': '获取竞选进展、政策立场和即将举行的活动的每周更新，直接发送到您的收件箱。',
    'community.enterEmail': '输入您的邮箱',
    'community.subscribe': '订阅',
    'community.privacyNote': '我们尊重您的隐私。随时取消订阅。',
    'community.bePartMovement': '成为运动的一部分',
    'community.realChange': '当社区团结在一起时，真正的改变就会发生。加入数千名为进步政策而战的伊利诺伊州居民。',
    'community.volunteerToday': '今天志愿',
    'community.contactUs': '联系我们',
    
    // Campaign Page  
    'campaign.howCanHelp': '您如何帮助？',
    'campaign.joinMovement': '加入我们的运动，为伊利诺伊州带来真正的变革。每一份贡献、每一小时的志愿服务和每一个声音在我们争取正义和平等的斗争中都很重要。',
    'campaign.buildFuture': '团结起来，我们可以为所有伊利诺伊州居民建设更美好的未来。',
    'campaign.volunteering': '志愿服务',
    'campaign.joinGrassroots': '加入我们在全州的草根努力',
    'campaign.phoneBank': '电话银行',
    'campaign.canvassing': '拉票',
    'campaign.eventPlanning': '活动策划',
    'campaign.digitalOutreach': '数字推广',
    'campaign.getStarted': '开始',
    'campaign.donations': '捐赠',
    'campaign.fuelCampaign': '为我们的竞选活动提供资金',
    'campaign.grassrootsSupport': '这场竞选由草根支持者资助，不接受企业政治行动委员会的资金。',
    'campaign.everyDollar': '每一美元都直接用于接触选民和传播我们的进步信息。',
    'campaign.secureActBlue': '通过安全ActBlue捐赠',
    'campaign.donateNow': '立即捐赠',
    'campaign.press': '新闻',
    'campaign.mediaInquiries': '媒体咨询和新闻发布',
    'campaign.pressContact': '新闻联系',
    'campaign.mediaKit': '媒体工具包',
    'campaign.pressReleases': '新闻发布',
    'campaign.interviewRequests': '采访请求',
    'campaign.contactPress': '联系新闻',
    
    // Volunteer Page
    'volunteer.joinMovement': '加入运动',
    'volunteer.volunteerDesc': '志愿者是我们竞选活动的生命线。无论您有一小时还是一天，都有适合您技能和兴趣的机会。',
    'volunteer.opportunities': '志愿机会',
    'volunteer.phoneBank': '电话银行',
    'volunteer.canvassing': '拉票',
    'volunteer.eventPlanning': '活动策划',
    'volunteer.digitalOutreach': '数字推广',
    'volunteer.signUp': '报名',
    'volunteer.firstName': '名字',
    'volunteer.lastName': '姓氏',
    'volunteer.email': '邮箱',
    'volunteer.phone': '电话',
    'volunteer.zipCode': '邮政编码',
    'volunteer.interests': '志愿兴趣',
    'volunteer.availability': '可用性',
    'volunteer.weekdays': '工作日',
    'volunteer.weekends': '周末',
    'volunteer.evenings': '晚上',
    'volunteer.experience': '相关经验',
    'volunteer.submit': '提交',
    
    // Footer
    'footer.paidForBy': '由Jump for Senate支付',
    'footer.connect': '联系',
    'footer.contact': '联系方式',
    'footer.signUpUpdates': '注册更新',
  },
  pl: {
    // Navigation
    'nav.home': 'Główna',
    'nav.about': 'O nas',
    'nav.policies': 'Polityki',
    'nav.campaign': 'Kampania',
    'nav.community': 'Społeczność',
    'nav.volunteer': 'Wolontariusz',
    
    // Homepage
    'home.title': 'Twój przyszły senator USA żyje wśród ludzi',
    'home.tagline': 'To nie czerwoni kontra niebiescy, to oligarchowie kontra ty.',
    'home.getInvolved': 'Zaangażuj się',
    'home.donate': 'Przekaż darowiznę',
    'home.quote': 'Kandyduję na senatora USA, bo wierzę, że rząd powinien promować równość dla wszystkich.',
    'home.fightingTitle': 'Walcząc o naszą przyszłość',
    'home.costOfLiving': 'Obniżanie kosztów życia',
    'home.costOfLivingDesc': 'Czynienie mieszkań, opieki zdrowotnej i edukacji dostępnymi dla każdej rodziny przez odważne działania polityczne.',
    'home.environment': 'Polityka środowiskowa',
    'home.environmentDesc': 'Ochrona naszej planety przy jednoczesnym tworzeniu dobrze płatnych zielonych miejsc pracy dla następnego pokolenia.',
    'home.pinkTax': 'Eliminacja różowego podatku',
    'home.pinkTaxDesc': 'Zakończenie dyskryminacji cenowej opartej na płci raz na zawsze przez federalne prawodawstwo.',
    'home.learnMore': 'Dowiedz się więcej',
    'home.theIssues': 'Problemy',
    'home.joinMovement': 'Dołącz do ruchu',
    'home.joinDesc': 'Razem możemy zbudować przyszłość, w której każda osoba ma szansę na rozwój.',
    'home.donateToday': 'Przekaż darowiznę dziś',
    'home.statsIllinois': 'Mieszkańcy Illinois',
    'home.statsElection': 'Rok Wyborczy',
    'home.statsVoice': 'Głos dla Zmiany',
    'home.readyFight': 'Gotowy na Walkę Razem?',
    'home.fightDesc': 'Ta kampania dotyczy budowania ruchu na rzecz zmiany. Dołącz do tysięcy mieszkańców Illinois, którzy są gotowi walczyć o lepszą przyszłość.',
    'home.supportCampaign': 'Wspieraj Kampanię',
    
    // About Page
    'about.meetJump': 'Poznaj Jump',
    'about.policies': 'Polityki',
    'about.policiesDesc': 'Kompleksowa platforma polityczna Jump koncentruje się na sprawiedliwości ekonomicznej, odpowiedzialności środowiskowej i równości dla wszystkich Amerykanów.',
    'about.viewPlatform': 'Zobacz Platformę',
    'about.getInvolved': 'Zaangażuj się',
    'about.myPolicies': 'Moje Polityki',
    'about.bioText': 'Jump urodził się i wychował w Chicago. Jako rodowity mieszkaniec Illinois jest wyjątkowo przygotowany do zrozumienia i rozwiązania problemów mieszkańców Illinois z klasy robotniczej.',
    'about.economicJustice': 'Sprawiedliwość Ekonomiczna',
    'about.healthcareAccess': 'Dostęp do Opieki Zdrowotnej',
    'about.workingClassFamilies': 'Rodziny Klasy Robotniczej',
    'about.climateAction': 'Działania Klimatyczne',
    'about.reproductiveRights': 'Prawa Reprodukcyjne',
    'about.readyToFight': 'Gotowy na Walkę Razem?',
    'about.buildingMovement': 'Ta kampania dotyczy budowania ruchu na rzecz zmiany. Dołącz do tysięcy mieszkańców Illinois, którzy są gotowi walczyć o lepszą przyszłość.',
    'about.joinMovement': 'Dołącz do Ruchu',
    'about.supportCampaign': 'Wspieraj Kampanię',
    
    // Policies Page
    'policies.myPolicies': 'Moje Polityki',
    'policies.championing': 'Promowanie Progresywnych Wartości dla Illinois',
    'policies.economicJusticeTitle': 'Sprawiedliwość Ekonomiczna',
    'policies.economicJusticeDesc': 'Walka o uczciwe płace, prawa pracowników i możliwości ekonomiczne budujące silne społeczności.',
    'policies.healthcareAccessTitle': 'Dostęp do Opieki Zdrowotnej',
    'policies.healthcareAccessDesc': 'Zapewnienie każdemu mieszkańcowi Illinois dostępu do przystępnej, wysokiej jakości opieki zdrowotnej jako podstawowego prawa.',
    'policies.educationEquityTitle': 'Równość Edukacyjna',
    'policies.educationEquityDesc': 'Inwestowanie w edukację publiczną i czynienie studiów przystępnymi dla rodzin robotniczych.',
    'policies.workingFamiliesTitle': 'Rodziny Robotnicze',
    'policies.workingFamiliesDesc': 'Wspieranie polityk pomagających rodzinom robotniczym prosperować w dzisiejszej gospodarce.',
    'policies.climateActionTitle': 'Działania Klimatyczne',
    'policies.climateActionDesc': 'Prowadzenie walki z zmianami klimatycznymi poprzez miejsca pracy w czystej energii i sprawiedliwość środowiskową.',
    
    // Community Page
    'community.joinCommunity': 'Dołącz do naszej społeczności',
    'community.connectWith': 'Połącz się z mieszkańcami Illinois budującymi oddolny ruch na rzecz sprawiedliwości ekonomicznej i progresywnych zmian.',
    'community.followCampaign': 'Śledź kampanię',
    'community.stayConnected': 'Pozostań w kontakcie z codziennymi aktualizacjami, treściami zza kulis i wydarzeniami na żywo',
    'community.socialMedia': 'Media społecznościowe',
    'community.tiktok': 'TikTok',
    'community.linkedin': 'LinkedIn',
    'community.youtube': 'YouTube',
    'community.merchandise': 'Gadżety',
    'community.orderMerch': 'Zamów gadżety',
    'community.showSupport': 'Pokaż swoje wsparcie oficjalnymi gadżetami kampanii',
    'community.tshirts': 'Koszulki',
    'community.buttonsStickers': 'Przypinki i naklejki',
    'community.yardSign': 'Zamów tabliczkę na podwórko',
    'community.stayInformed': 'Bądź na bieżąco',
    'community.weeklyUpdates': 'Otrzymuj cotygodniowe aktualizacje o postępach kampanii, stanowiskach politycznych i nadchodzących wydarzeniach dostarczone do twojej skrzynki odbiorczej.',
    'community.enterEmail': 'Wpisz swój email',
    'community.subscribe': 'Subskrybuj',
    'community.privacyNote': 'Szanujemy twoją prywatność. Anuluj subskrypcję w dowolnym momencie.',
    'community.bePartMovement': 'Bądź częścią ruchu',
    'community.realChange': 'Prawdziwa zmiana następuje, gdy społeczności organizują się razem. Dołącz do tysięcy mieszkańców Illinois walczących o progresywne polityki.',
    'community.volunteerToday': 'Zostań wolontariuszem dziś',
    'community.contactUs': 'Skontaktuj się z nami',
    
    // Campaign Page  
    'campaign.howCanHelp': 'Jak możesz pomóc?',
    'campaign.joinMovement': 'Dołącz do naszego ruchu, aby przynieść prawdziwą zmianę do Illinois. Każdy wkład, każda godzina wolontariatu i każdy głos ma znaczenie w naszej walce o sprawiedliwość i równość.',
    'campaign.buildFuture': 'Razem możemy zbudować lepszą przyszłość dla wszystkich mieszkańców Illinois.',
    'campaign.volunteering': 'Wolontariat',
    'campaign.joinGrassroots': 'Dołącz do naszych oddolnych działań w całym stanie',
    'campaign.phoneBank': 'Bank telefoniczny',
    'campaign.canvassing': 'Agitacja',
    'campaign.eventPlanning': 'Planowanie wydarzeń',
    'campaign.digitalOutreach': 'Zasięg cyfrowy',
    'campaign.getStarted': 'Zacznij',
    'campaign.donations': 'Darowizny',
    'campaign.fuelCampaign': 'Sfinansuj naszą kampanię',
    'campaign.grassrootsSupport': 'Ta kampania jest finansowana przez oddolnych zwolenników i nie przyjmuje pieniędzy od korporacyjnych PAC.',
    'campaign.everyDollar': 'Każdy dolar idzie bezpośrednio na dotarcie do wyborców i rozpowszechnienie naszego progresywnego przesłania.',
    'campaign.secureActBlue': 'Bezpieczna darowizna ActBlue',
    'campaign.donateNow': 'Przekaż darowiznę teraz',
    'campaign.press': 'Prasa',
    'campaign.mediaInquiries': 'Zapytania medialne i komunikaty prasowe',
    'campaign.pressContact': 'Kontakt prasowy',
    'campaign.mediaKit': 'Zestaw medialny',
    'campaign.pressReleases': 'Komunikaty prasowe',
    'campaign.interviewRequests': 'Prośby o wywiady',
    'campaign.contactPress': 'Skontaktuj się z prasą',
    
    // Volunteer Page
    'volunteer.joinMovement': 'Dołącz do ruchu',
    'volunteer.volunteerDesc': 'Wolontariusze są linią życia naszej kampanii. Niezależnie od tego, czy masz godzinę czy dzień, są możliwości dopasowane do twoich umiejętności i zainteresowań.',
    'volunteer.opportunities': 'Możliwości wolontariatu',
    'volunteer.phoneBank': 'Bank telefoniczny',
    'volunteer.canvassing': 'Agitacja',
    'volunteer.eventPlanning': 'Planowanie wydarzeń',
    'volunteer.digitalOutreach': 'Zasięg cyfrowy',
    'volunteer.signUp': 'Zarejestruj się',
    'volunteer.firstName': 'Imię',
    'volunteer.lastName': 'Nazwisko',
    'volunteer.email': 'Email',
    'volunteer.phone': 'Telefon',
    'volunteer.zipCode': 'Kod pocztowy',
    'volunteer.interests': 'Zainteresowania wolontariackie',
    'volunteer.availability': 'Dostępność',
    'volunteer.weekdays': 'Dni powszednie',
    'volunteer.weekends': 'Weekendy',
    'volunteer.evenings': 'Wieczory',
    'volunteer.experience': 'Odpowiednie doświadczenie',
    'volunteer.submit': 'Wyślij',
    
    // Footer
    'footer.paidForBy': 'Opłacone przez Jump for Senate',
    'footer.connect': 'Połącz',
    'footer.contact': 'Kontakt',
    'footer.signUpUpdates': 'Zapisz się na aktualizacje',
  },
  ar: {
    // Navigation
    'nav.home': 'الرئيسية',
    'nav.about': 'عن',
    'nav.policies': 'السياسات',
    'nav.campaign': 'الحملة',
    'nav.community': 'المجتمع',
    'nav.volunteer': 'متطوع',
    
    // Homepage
    'home.title': 'عضو مجلس الشيوخ الأمريكي المستقبلي يعيش بين الناس',
    'home.tagline': 'ليس الأحمر ضد الأزرق، إنه أصحاب الاحتكار ضدك.',
    'home.getInvolved': 'شارك',
    'home.donate': 'تبرع',
    'home.quote': 'أترشح لمجلس الشيوخ الأمريكي لأنني أؤمن أن الحكومة يجب أن تعزز المساواة للجميع.',
    'home.fightingTitle': 'نقاتل من أجل مستقبلنا',
    'home.costOfLiving': 'خفض تكلفة المعيشة',
    'home.costOfLivingDesc': 'جعل الإسكان والرعاية الصحية والتعليم في متناول كل عائلة من خلال العمل السياسي الجريء.',
    'home.environment': 'السياسة البيئية',
    'home.environmentDesc': 'حماية كوكبنا مع خلق وظائف خضراء عالية الأجر للجيل القادم.',
    'home.pinkTax': 'إلغاء الضريبة الوردية',
    'home.pinkTaxDesc': 'إنهاء التمييز في الأسعار القائم على النوع الاجتماعي مرة واحدة وإلى الأبد من خلال التشريع الفيدرالي.',
    'home.learnMore': 'تعلم المزيد',
    'home.theIssues': 'القضايا',
    'home.joinMovement': 'انضم للحركة',
    'home.joinDesc': 'معًا، يمكننا بناء مستقبل حيث كل شخص لديه الفرصة للازدهار.',
    'home.donateToday': 'تبرع اليوم',
    'home.statsIllinois': 'سكان إلينوي',
    'home.statsElection': 'سنة الانتخابات',
    'home.statsVoice': 'صوت للتغيير',
    'home.readyFight': 'مستعد للقتال معًا؟',
    'home.fightDesc': 'هذه الحملة تتعلق ببناء حركة للتغيير. انضم إلى آلاف سكان إلينوي الذين هم مستعدون للقتال من أجل مستقبل أفضل.',
    'home.supportCampaign': 'ادعم الحملة',
    
    // About Page
    'about.meetJump': 'تعرف على Jump',
    'about.policies': 'السياسات',
    'about.policiesDesc': 'منصة السياسة الشاملة لـ Jump تركز على العدالة الاقتصادية والمسؤولية البيئية والمساواة لجميع الأمريكيين.',
    'about.viewPlatform': 'عرض المنصة',
    'about.getInvolved': 'شارك',
    'about.myPolicies': 'سياساتي',
    'about.bioText': 'ولد وترعرع Jump في شيكاغو. كمواطن أصلي من إلينوي، فهو مجهز بشكل فريد لفهم ومعالجة تحديات سكان إلينوي من الطبقة العاملة.',
    'about.economicJustice': 'العدالة الاقتصادية',
    'about.healthcareAccess': 'الرعاية الصحية',
    'about.workingClassFamilies': 'عائلات الطبقة العاملة',
    'about.climateAction': 'العمل المناخي',
    'about.reproductiveRights': 'الحقوق الإنجابية',
    'about.readyToFight': 'مستعد للقتال معًا؟',
    'about.buildingMovement': 'هذه الحملة تتعلق ببناء حركة للتغيير. انضم إلى آلاف سكان إلينوي الذين هم مستعدون للقتال من أجل مستقبل أفضل.',
    'about.joinMovement': 'انضم للحركة',
    'about.supportCampaign': 'ادعم الحملة',
    
    // Policies Page
    'policies.myPolicies': 'سياساتي',
    'policies.championing': 'الدفاع عن القيم التقدمية لإلينوي',
    'policies.economicJusticeTitle': 'العدالة الاقتصادية',
    'policies.economicJusticeDesc': 'النضال من أجل الأجور العادلة وحقوق العمال والفرص الاقتصادية التي تبني مجتمعات قوية.',
    'policies.healthcareAccessTitle': 'الرعاية الصحية',
    'policies.healthcareAccessDesc': 'ضمان حصول كل مواطن في إلينوي على رعاية صحية عالية الجودة وبأسعار معقولة كحق أساسي.',
    'policies.educationEquityTitle': 'المساواة في التعليم',
    'policies.educationEquityDesc': 'الاستثمار في التعليم العام وجعل الكلية في متناول العائلات العاملة.',
    'policies.workingFamiliesTitle': 'العائلات العاملة',
    'policies.workingFamiliesDesc': 'دعم السياسات التي تساعد العائلات العاملة على الازدهار في اقتصاد اليوم.',
    'policies.climateActionTitle': 'العمل المناخي',
    'policies.climateActionDesc': 'قيادة المعركة ضد تغير المناخ بوظائف الطاقة النظيفة والعدالة البيئية.',
    
    // Community Page
    'community.joinCommunity': 'انضم إلى مجتمعنا',
    'community.connectWith': 'تواصل مع سكان إلينوي الذين يبنون حركة شعبية للعدالة الاقتصادية والتغيير التقدمي.',
    'community.followCampaign': 'تابع الحملة',
    'community.stayConnected': 'ابق على اتصال مع التحديثات اليومية والمحتوى خلف الكواليس والأحداث المباشرة',
    'community.socialMedia': 'وسائل التواصل الاجتماعي',
    'community.tiktok': 'تيك توك',
    'community.linkedin': 'لينكد إن',
    'community.youtube': 'يوتيوب',
    'community.merchandise': 'البضائع',
    'community.orderMerch': 'اطلب البضائع',
    'community.showSupport': 'أظهر دعمك ببضائع الحملة الرسمية',
    'community.tshirts': 'قمصان',
    'community.buttonsStickers': 'أزرار وملصقات',
    'community.yardSign': 'اطلب لافتة فناء',
    'community.stayInformed': 'ابق مطلعًا',
    'community.weeklyUpdates': 'احصل على تحديثات أسبوعية حول تقدم الحملة والمواقف السياسية والأحداث القادمة مباشرة إلى صندوق الوارد الخاص بك.',
    'community.enterEmail': 'أدخل بريدك الإلكتروني',
    'community.subscribe': 'اشترك',
    'community.privacyNote': 'نحترم خصوصيتك. إلغاء الاشتراك في أي وقت.',
    'community.bePartMovement': 'كن جزءًا من الحركة',
    'community.realChange': 'التغيير الحقيقي يحدث عندما تتنظم المجتمعات معًا. انضم إلى آلاف سكان إلينوي الذين يقاتلون من أجل السياسات التقدمية.',
    'community.volunteerToday': 'تطوع اليوم',
    'community.contactUs': 'اتصل بنا',
    
    // Campaign Page  
    'campaign.howCanHelp': 'كيف يمكنك المساعدة؟',
    'campaign.joinMovement': 'انضم إلى حركتنا لجلب تغيير حقيقي إلى إلينوي. كل مساهمة وكل ساعة تطوع وكل صوت مهم في كفاحنا من أجل العدالة والمساواة.',
    'campaign.buildFuture': 'معًا، يمكننا بناء مستقبل أفضل لجميع سكان إلينوي.',
    'campaign.volunteering': 'التطوع',
    'campaign.joinGrassroots': 'انضم إلى جهودنا الشعبية في جميع أنحاء الولاية',
    'campaign.phoneBank': 'مصرف الهاتف',
    'campaign.canvassing': 'التجول الانتخابي',
    'campaign.eventPlanning': 'تخطيط الأحداث',
    'campaign.digitalOutreach': 'التوعية الرقمية',
    'campaign.getStarted': 'ابدأ',
    'campaign.donations': 'التبرعات',
    'campaign.fuelCampaign': 'موّل حملتنا',
    'campaign.grassrootsSupport': 'هذه الحملة ممولة من قبل مؤيدين شعبيين ولا تقبل أموالاً من اللجان السياسية للشركات.',
    'campaign.everyDollar': 'كل دولار يذهب مباشرة للوصول إلى الناخبين ونشر رسالتنا التقدمية.',
    'campaign.secureActBlue': 'تبرع آمن عبر ActBlue',
    'campaign.donateNow': 'تبرع الآن',
    'campaign.press': 'الصحافة',
    'campaign.mediaInquiries': 'استفسارات الإعلام والبيانات الصحفية',
    'campaign.pressContact': 'جهة الاتصال الصحفية',
    'campaign.mediaKit': 'حقيبة الإعلام',
    'campaign.pressReleases': 'البيانات الصحفية',
    'campaign.interviewRequests': 'طلبات المقابلات',
    'campaign.contactPress': 'اتصل بالصحافة',
    
    // Volunteer Page
    'volunteer.joinMovement': 'انضم للحركة',
    'volunteer.volunteerDesc': 'المتطوعون هم شريان الحياة لحملتنا. سواء كان لديك ساعة أو يوم، هناك فرص تناسب مهاراتك واهتماماتك.',
    'volunteer.opportunities': 'فرص التطوع',
    'volunteer.phoneBank': 'مصرف الهاتف',
    'volunteer.canvassing': 'التجول الانتخابي',
    'volunteer.eventPlanning': 'تخطيط الأحداث',
    'volunteer.digitalOutreach': 'التوعية الرقمية',
    'volunteer.signUp': 'سجل',
    'volunteer.firstName': 'الاسم الأول',
    'volunteer.lastName': 'اسم العائلة',
    'volunteer.email': 'البريد الإلكتروني',
    'volunteer.phone': 'الهاتف',
    'volunteer.zipCode': 'الرمز البريدي',
    'volunteer.interests': 'اهتمامات التطوع',
    'volunteer.availability': 'التوفر',
    'volunteer.weekdays': 'أيام الأسبوع',
    'volunteer.weekends': 'عطلات نهاية الأسبوع',
    'volunteer.evenings': 'المساء',
    'volunteer.experience': 'الخبرة ذات الصلة',
    'volunteer.submit': 'إرسال',
    
    // Footer
    'footer.paidForBy': 'مدفوع من قبل Jump for Senate',
    'footer.connect': 'تواصل',
    'footer.contact': 'اتصال',
    'footer.signUpUpdates': 'اشترك في التحديثات',
  },
};

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<Language>('en');

  const t = (key: string) => {
    return translations[language][key as keyof typeof translations['en']] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}