name: Seed Database

on:
  workflow_dispatch:  # This allows manual triggering from GitHub UI

jobs:
  seed:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'  # or your preferred version

      - name: Install dependencies
        run: npm install

      - name: Run seed script
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        run: |
          npx ts-node server/seedContent.ts
